### ISSUE TITLE
[Bug]无法使用websocket连接mirai，websockets.exceptions.NegotiationError: Unsupported extension: name = frame-log, params = []

### ISSUE THREAD

**Issue by 857950459** [nonebot/adapter-mirai#1]
## 请确认：

* [x] 问题的标题明确
* [x] 我翻阅过其他的 issue 并且找不到类似的问题
* [x] 我已经阅读了[相关文档](https://github.com/project-mirai/mirai-api-http#%E6%96%87%E6%A1%A3) 并仍然认为这是一个Bug

# Bug

## 问题

无法使用websocker连接mirai，提示websockets.exceptions.NegotiationError: Unsupported extension: name = frame-log, params = []

修改了pydantic版本，也修改适配器的代码，不知道是哪里改得不对，请大佬们帮看看，谢谢。

我尝试改为aiohttp驱动器之后，错误只会出现 错误一 跟 错误四，但是使用echo插件的时候，仍然会提示一样的错误

## 如何复现

使用nb create 创建一个机器人，选择如下

[?] Project Name: AAA
[?] Which adapter(s) would you like to use? Mirai (mirai-api-http v2 协议适配)
[?] Which driver(s) would you like to use? HTTPX (HTTPX 驱动器), websockets (websockets 驱动器)
[?] Install dependencies now? y
[?] Create virtual environment? y

修改.env.prod配置

DRIVER=~httpx+~websockets
MIRAI_CLIENTS='
[
  {
    "host": "x.x.x.x",
    "port": "xxxx",
    "account": xxxxxxxxx,
    "verify_key": "xxxxxxxxxx"
  }
]
'

运行bot
cd AAA
nb run

会出现 （详细查看下文的日志错误一）
NameError: Fields must not use names with leading underscores; e.g., use 'Group__kind' instead of '_Group__kind'.

修改了pydantic~=1.10版本，最终安装的版本是pydantic-1.10.17
再次运行，会出现连接不是ws的错误（详细查看下文的日志错误二）

websockets.exceptions.InvalidURI: https://x.x.x.x:xxxxx/all?qq=xxxxxxxxx&verifyKey=xxxxxxxxxx isn't a valid URI: scheme isn't ws or wss

修改nonebot/adapters/mirai/config.py的第25行
将http修改为ws
    def ws_url(self):
        return str(
            (URL(f"ws://{self.host}:{self.port}") / "all").with_query(
                {"qq": self.account, "verifyKey": self.verify_key}
            )
        )

再次连接，会出现（详细查看下文的日志错误三）
websockets.exceptions.NegotiationError: Unsupported extension: name = frame-log, params = []

尝试跳过协商字段
websockets/legacy/client.py的196行
for name, response_params in parsed_header_values:
    if name == 'frame-log':
        continue
    for extension_factory in available_extensions:
        ...

再次运行，虽然能正常运行，能收到信息，但是使用echo插件给机器人测试会出现报错（详细查看下文的日志错误四）

AttributeError: type object 'Text' has no attribute '__rmapping__'

## 使用环境:
- 操作系统 (Windows/Linux/Mac):Linux 
- Python 版本: 3.11
- Nonebot2 版本: 2.3.1
- 适配器版本: 2.3.1
- 使用的 mirai-api-http 版本: 2.10.0

## 配置文件

```dotenv
```
DRIVER=~httpx+~websockets
MIRAI_CLIENTS='
[
  {
    "host": "x.x.x.x",
    "port": "xxxx",
    "account": xxxxxxxxx,
    "verify_key": "xxxxxxxxxx"
  }
]
'

## 日志/截图

1.报错一
(.env) root@vpc1:~/bot/AAA# nb run
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/adapters/mirai/__init__.py", line 1, in <module>
    from .bot import Bot as Bot
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/adapters/mirai/bot.py", line 19, in <module>
    from .message import Image, Video, Voice, Message, MessageSegment
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/adapters/mirai/message.py", line 14, in <module>
    from .model import Member
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/adapters/mirai/model/__init__.py", line 1, in <module>
    from .common import Profile as Profile
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/adapters/mirai/model/common.py", line 11, in <module>
    from .relationship import Group, Friend
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/adapters/mirai/model/relationship.py", line 45, in <module>
    class Group(ModelBase):
  File "/root/bot/.env/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 96, in __new__
    private_attributes = inspect_namespace(
                         ^^^^^^^^^^^^^^^^^^
  File "/root/bot/.env/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 376, in inspect_namespace
    raise NameError(
NameError: Fields must not use names with leading underscores; e.g., use 'Group__kind' instead of '_Group__kind'.

2.报错二
root@test:~/bot/AAA# nb run
Using python: /root/bot/AAA/.venv/bin/python
07-02 10:30:18 [SUCCESS] nonebot | NoneBot is initializing...
07-02 10:30:18 [INFO] nonebot | Current Env: prod
07-02 10:30:18 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
07-02 10:30:18 [SUCCESS] nonebot | Running NoneBot...
07-02 10:30:18 [INFO] nonebot | Application startup completed.
07-02 10:30:18 [ERROR] nonebot | Mirai | Error while setup websocket to https://x.x.x.x:xxxx/all?qq=xxxxxxx&verifyKey=xxxxxxxxx. Trying to reconnect...
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/bot/AAA/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/bot/AAA/.venv/lib/python3.10/site-packages/nonebot/drivers/none.py", line 56, in run
    loop.run_until_complete(self._serve())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/bot/AAA/.venv/lib/python3.10/site-packages/nonebot/adapters/mirai/adapter.py", line 107, in ws
    async with self.websocket(req) as ws:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/root/bot/AAA/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/adapter.py", line 99, in websocket
    async with self.driver.websocket(setup) as ws:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/root/bot/AAA/.venv/lib/python3.10/site-packages/nonebot/drivers/websockets.py", line 72, in websocket
    connection = Connect(
  File "/root/bot/AAA/.venv/lib/python3.10/site-packages/websockets/legacy/client.py", line 479, in __init__
    wsuri = parse_uri(uri)
  File "/root/bot/AAA/.venv/lib/python3.10/site-packages/websockets/uri.py", line 77, in parse_uri
    raise exceptions.InvalidURI(uri, "scheme isn't ws or wss")
websockets.exceptions.InvalidURI: https://x.x.x.x:xxxxx/all?qq=xxxxxxxxx&verifyKey=xxxxxxxxxx isn't a valid URI: scheme isn't ws or wss

3.报错三
(.env) root@vpc1:~/bot/AAA# nb run
07-02 10:34:07 [SUCCESS] nonebot | NoneBot is initializing...
07-02 10:34:07 [INFO] nonebot | Current Env: prod
07-02 10:34:07 [SUCCESS] nonebot | Running NoneBot...
07-02 10:34:07 [INFO] nonebot | Application startup completed.
07-02 10:34:07 [ERROR] nonebot | Mirai | Error while setup websocket to ws://x.x.x.x:xxxxx/all?qq=xxxxxxxx&verifyKey=xxxxxxxxx. Trying to reconnect...
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/drivers/none.py", line 56, in run
    loop.run_until_complete(self._serve())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/adapters/mirai/adapter.py", line 107, in ws
    async with self.websocket(req) as ws:
  File "/usr/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/internal/adapter/adapter.py", line 99, in websocket
    async with self.driver.websocket(setup) as ws:
  File "/usr/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/drivers/websockets.py", line 77, in websocket
    async with connection as ws:
  File "/root/bot/.env/lib/python3.11/site-packages/websockets/legacy/client.py", line 631, in __aenter__
    return await self
  File "/root/bot/.env/lib/python3.11/site-packages/websockets/legacy/client.py", line 649, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/root/bot/.env/lib/python3.11/site-packages/websockets/legacy/client.py", line 656, in __await_impl__
    await protocol.handshake(
  File "/root/bot/.env/lib/python3.11/site-packages/websockets/legacy/client.py", line 331, in handshake
    self.extensions = self.process_extensions(
  File "/root/bot/.env/lib/python3.11/site-packages/websockets/legacy/client.py", line 220, in process_extensions
    raise NegotiationError(
websockets.exceptions.NegotiationError: Unsupported extension: name = frame-log, params = []

4.报错四
(.env) root@vpc1:~/bot/AAA# nb run
07-02 10:37:58 [SUCCESS] nonebot | NoneBot is initializing...
07-02 10:37:58 [INFO] nonebot | Current Env: prod
07-02 10:37:58 [SUCCESS] nonebot | Running NoneBot...
07-02 10:37:58 [INFO] nonebot | Application startup completed.
07-02 10:37:58 [INFO] nonebot | Mirai | Bot xxxxxxxxx connected
07-02 10:37:58 [SUCCESS] nonebot | Mirai | Bot xxxxxxxxx session key got.
07-02 10:37:59 [SUCCESS] nonebot | Mirai xxxxxxxxx | [GroupMessage]: GroupMessage
07-02 10:38:23 [SUCCESS] nonebot | Mirai xxxxxxxxx | [GroupMessage]: GroupMessage
07-02 10:38:33 [SUCCESS] nonebot | Mirai xxxxxxxxx | [FriendInputStatusChangedEvent]: FriendInputStatusChangedEvent
07-02 10:38:34 [SUCCESS] nonebot | Mirai xxxxxxxxx | [FriendInputStatusChangedEvent]: FriendInputStatusChangedEvent
07-02 10:38:34 [SUCCESS] nonebot | Mirai xxxxxxxxx | [FriendInputStatusChangedEvent]: FriendInputStatusChangedEvent
07-02 10:38:34 [ERROR] nonebot | Mirai | Error while process data from websocket ws://x.x.x.x:xxxxx/all?qq=xxxxxxxxx&verifyKey=xxxxxxxxxx. Trying to reconnect...
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/drivers/none.py", line 56, in run
    loop.run_until_complete(self._serve())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/adapters/mirai/adapter.py", line 124, in ws
    await self._loop(info, ws)
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/adapters/mirai/adapter.py", line 192, in _loop
    event = type_validate_python(EVENT_CLASSES[event_type], body)
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/compat.py", line 372, in type_validate_python
    return parse_obj_as(type_, data)
  File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
    return model_type(__root__=obj).__root__
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "pydantic/main.py", line 1074, in pydantic.main.validate_model
    v_, errors_ = field.validate(value, values, loc=field.alias, cls=cls_)
  File "pydantic/fields.py", line 881, in pydantic.fields.ModelField.validate
    v, errors = self._validate_singleton(v, values, loc, cls)
  File "pydantic/fields.py", line 1098, in pydantic.fields.ModelField._validate_singleton
    return self._apply_validators(v, values, loc, cls, self.validators)
  File "pydantic/fields.py", line 1154, in pydantic.fields.ModelField._apply_validators
    v = validator(cls, v, values, self, self.model_config)
  File "pydantic/class_validators.py", line 337, in pydantic.class_validators._generic_validator_basic.lambda13
    return lambda cls, v, values, field, config: validator(v)
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/internal/adapter/event.py", line 31, in validate
    return super().validate(value)
  File "pydantic/main.py", line 711, in pydantic.main.BaseModel.validate
    return cls(**value)
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/adapters/mirai/model/base.py", line 17, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "pydantic/main.py", line 1048, in pydantic.main.validate_model
    input_data = validator(cls_, input_data)
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/adapters/mirai/event.py", line 100, in generate_message
    values["message"] = Message.from_elements(values["messageChain"])
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/adapters/mirai/message.py", line 768, in from_elements
    msg.append(TYPE_MAPPING[element["type"]].parse(element))
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/adapters/mirai/message.py", line 38, in parse
    {cls.__rmapping__.get(k, k): v for k, v in raw.items() if k != "type"},
  File "/root/bot/.env/lib/python3.11/site-packages/nonebot/adapters/mirai/message.py", line 38, in <dictcomp>
    {cls.__rmapping__.get(k, k): v for k, v in raw.items() if k != "type"},
AttributeError: type object 'Text' has no attribute '__rmapping__'
07-02 10:38:34 [INFO] nonebot | Mirai | Bot xxxxxxxx connected
07-02 10:38:34 [SUCCESS] nonebot | Mirai | Bot xxxxxxxx session key got.

**Comment by RF-Tar-Railt** [comment]
kind在2.3.2修了

**Comment by RF-Tar-Railt** [comment]
关于 websockets.exceptions.NegotiationError 这个问题，你可以先使用aiohttp适配器，然后去 nonebot2 主仓库下发起关于此的 issue
